apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://grafana-loki:3100
    access: proxy
    isDefault: false

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090/prometheus
    access: proxy
    isDefault: true
