apiVersion: v2
name: joblensai-notification
description: JobLens AI Notification Service - Notification service
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Mayank Gupta
keywords:
  - joblensai
  - notification
  - api
