FROM node:24-alpine

RUN corepack enable
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

# Copy workspace configuration and lockfile
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# Copy package.json files for the service and its local dependencies
COPY apps/auth/package.json ./apps/auth/
COPY packages/shared/package.json ./packages/shared/

# Install dependencies
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install

# We don't COPY the source code here because we will mount it as a volume
# in docker-compose.

EXPOSE 5000

CMD ["pnpm", "--filter", "auth", "dev"]
