import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ModeToggle } from "./mode-toggle";
import logo from "@/assets/joblensai.svg";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import { cn } from "@/lib/utils";

const NavBar = () => {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 transition-all duration-300">
      <div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-8">
        <div className="flex items-center gap-2 group">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-primary-foreground font-black text-xs transition-transform group-hover:scale-105 shadow-xl shadow-primary/20">
              <img src={logo} alt="JobLens AI" className="w-6 h-6 invert dark:invert-0" />
            </div>
            <span className="font-bold text-xl tracking-tight hidden sm:inline-block">
              JobLens AI
            </span>
          </Link>
        </div>

        <div className="hidden md:flex flex-1 justify-center">
          <NavigationMenu>
            <NavigationMenuList>
              <NavigationMenuItem>
                <NavigationMenuTrigger className="bg-transparent hover:bg-muted/50 transition-colors">
                  Features
                </NavigationMenuTrigger>
                <NavigationMenuContent>
                  <ul className="grid gap-3 p-6 md:w-100 lg:w-125 lg:grid-cols-[.75fr_1fr]">
                    <ListItem href="#features" title="AI Outreach">
                      Automated personalized handshake generated by LLM.
                    </ListItem>
                    <ListItem href="#features" title="Skill DNA">
                      Matching based on technical skill fingerprints.
                    </ListItem>
                    <ListItem href="#features" title="Real-time">
                      Instant notifications when you both swipe right.
                    </ListItem>
                  </ul>
                </NavigationMenuContent>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <a href="#how-it-works">
                  <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                    How it Works
                  </NavigationMenuLink>
                </a>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <a href="#pricing">
                  <NavigationMenuLink className={navigationMenuTriggerStyle()}>
                    Pricing
                  </NavigationMenuLink>
                </a>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </div>

        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 border-l pl-4 border-border/50">
            <Button
              variant="ghost"
              size="sm"
              asChild
              className="text-sm font-semibold border border-foreground"
            >
              <Link to="/login">Log in</Link>
            </Button>
            <Button
              size="sm"
              className="hidden sm:flex font-semibold shadow-md active:scale-95 transition-all"
              asChild
            >
              <Link to="/signup">Get Started</Link>
            </Button>
            <ModeToggle />
          </div>
        </div>
      </div>
    </header>
  );
};

interface ListItemProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  title: string;
}

const ListItem = ({ className, title, children, ...props }: ListItemProps) => {
  return (
    <li>
      <NavigationMenuLink asChild>
        <a
          className={cn(
            "block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground",
            className
          )}
          {...props}
        >
          <div className="text-sm font-medium leading-none">{title}</div>
          <p className="line-clamp-2 text-sm leading-snug text-muted-foreground">{children}</p>
        </a>
      </NavigationMenuLink>
    </li>
  );
};

export default NavBar;
