apiVersion: v2
name: joblensai-chart
description: A Helm chart for joblensai microservices
type: application
version: 1.0.0
dependencies:
  - name: joblensai-auth-chart
    alias: auth
    version: 1.0.0
    repository: file://../../apps/auth/chart
  - name: joblensai-backend-chart
    alias: backend
    version: 1.0.0
    repository: file://../../apps/backend/chart
  - name: joblensai-agent-service-chart
    alias: agent-service
    version: 1.0.0
    repository: file://../../apps/agent-service/chart
  - name: joblensai-payment-chart
    alias: payment
    version: 1.0.0
    repository: file://../../apps/payment/chart
  - name: joblensai-notification-chart
    alias: notification
    version: 1.0.0
    repository: file://../../apps/notification/chart
  - name: joblensai-web-chart
    alias: web
    version: 1.0.0
    repository: file://../../apps/web/chart
