apiVersion: v2
name: joblensai-web
description: JobLens AI Web Service - Web service
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Mayank Gupta
keywords:
  - joblensai
  - web
  - frontend
