apiVersion: v1
kind: Secret
metadata:
  name: joblensai-secrets
  namespace: joblensai
type: Opaque
stringData:
  # MongoDB
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root1234
  MONGODB_URI: mongodb://root:root1234@mongodb:27017/joblensai?authSource=admin
  # Redis
  REDIS_URL: redis://redis:6379
  # Minio
  MINIO_ROOT_USER: root1234
  MINIO_ROOT_PASSWORD: root1234
  MINIO_ENDPOINT: http://minio:9000
