apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joblensai-agent-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: joblensai
  source:
    repoURL: https://github.com/mayankgupta1008/joblensai-2
    targetRevision: main
    path: apps/agent-service/chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: joblensai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
