global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    scrape_interval: 15s
    metrics_path: "/api/backend/metrics"
    static_configs:
      - targets: ["backend:5001"]

  - job_name: "auth"
    scrape_interval: 15s
    metrics_path: "/api/auth/metrics"
    static_configs:
      - targets: ["auth:5003"]

  - job_name: "agent-service"
    scrape_interval: 15s
    metrics_path: "/api/agent-service/metrics"
    static_configs:
      - targets: ["agent-service:5002"]

  - job_name: "payment-service"
    scrape_interval: 15s
    metrics_path: "/api/payment/metrics"
    static_configs:
      - targets: ["payment-service:5004"]

  - job_name: "notification-service"
    scrape_interval: 15s
    metrics_path: "/api/notification/metrics"
    static_configs:
      - targets: ["notification-service:5005"]
