apiVersion: v2
name: joblensai-payment
description: JobLens AI Payment Service - Payment service
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Mayank Gupta
keywords:
  - joblensai
  - payment
  - api
