FROM node:24-alpine

RUN corepack enable
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

# Copy workspace configuration and lockfile
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

# Copy package.json files for the service and its local dependencies
COPY apps/payment/package.json ./apps/payment/
COPY packages/shared/package.json ./packages/shared/
COPY packages/eslint-config/package.json ./packages/eslint-config/

# Install dependencies
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install

# We don't COPY the source code here because we will mount it as a volume
# in docker-compose.

EXPOSE 5004

CMD ["pnpm", "--filter", "payment", "dev"]
